### ISSUE TITLE
Workspace diagnostics shows only open buffers for ts files with tsserver and null-ls

### ISSUE THREAD

**Issue by rphuber** [folke/trouble.nvim#192] opened 2022-06-25 11:24 UTC
Using both tsserver and null-ls with prettier and eslint I only get diagnostic reports from open buffers instead of the entire project.  I read in another issue that it seems to be an issue with tsserver but was wondering if this was an issue with the null-ls plugin as well?  Any feedback would be helpful.  Thanks!

**Comment by joelxr** [comment] 2022-07-26 15:26
Same thing happens to me after fresh installing it.

**Comment by Alex-vZyl** [comment] 2022-10-09 10:28
Duplicate of #107?

**Comment by folke** [comment] 2022-10-09 11:18
This has nothing to do with Trouble. Most language servers only show issue from opened files

**Closed by folke** 2022-10-09 11:18 UTC

**Comment by pencilcheck** [comment] 2023-03-21 19:20
Well, if that's the case, it shouldn't be called workspace, it should be called lsp-wide instead. this is misleading.

**Comment by folke** [comment] 2023-03-22 07:59
@pencilcheck it is called workspace diagnostics in the lsp spec, so that's how it will be called in trouble. ok?
