### ISSUE TITLE
bug v3: trouble.open runs error in telescope

### ISSUE THREAD

**Issue by ShiChenCong** [folke/trouble.nvim#393] opened 2024-03-29 08:16 UTC
### Did you check docs and existing issues?

- [X] I have read all the trouble.nvim docs
- [X] I have searched the existing issues of trouble.nvim
- [X] I have searched the existing issues of plugins related to this issue

### Neovim version (nvim -v)

NVIM v0.10.0-dev-2663+gc1c6c1ee1

### Operating system/version

14.2.1 (23C71)

### Describe the bug

<img width="1436" alt="image" src="https://github.com/folke/trouble.nvim/assets/22486446/3ac7b064-4be6-4fe0-a155-9c244eb90e90">

### Steps To Reproduce

1. telescope config
```
local telescope = require("telescope")

telescope.setup({
  defaults = {
    mappings = {
      i = { ["<c-t>"] = trouble.open },
      n = { ["<c-t>"] = trouble.open },
    },
  },
})
```
2. trouble config
```
require('trouble').setup({
})
```
3. select multiple file,cause the error
<img width="1436" alt="image" src="https://github.com/folke/trouble.nvim/assets/22486446/b142fc89-5121-430e-99dd-5ac4ada2e824">

### Expected Behavior

not show error

**Comment by folke** [comment] 2024-03-29 08:54
My bad, the code example was wrong. Just updated the docs.
Should be `sources` instead of `source`

```lua
local trouble = require("trouble.sources.telescope")

local telescope = require("telescope")

telescope.setup({
  defaults = {
    mappings = {
      i = { ["<c-t>"] = trouble.open },
      n = { ["<c-t>"] = trouble.open },
    },
  },
})
```

**Comment by ShiChenCong** [comment] 2024-03-29 08:58
I was already used `sources` before commit this issue
```
local trouble = require("trouble.sources.telescope")
```
same error

**Comment by folke** [comment] 2024-03-29 09:06
Are you sure that `trouble` variable is the one pointing to ` require("trouble.sources.telescope")` and not to `require("trouble")`?

**Comment by ShiChenCong** [comment] 2024-03-29 09:11
yes, https://github.com/ShiChenCong/.dotfiles/blob/4ea1d1a61542e4f9603fc58bb789139170a42cc2/nvim/lua/conf/telescope.lua#L4

**Comment by ShiChenCong** [comment] 2024-03-29 09:21
1. select multiple file in telescope window
2. press `<a-q>` which is executing `trouble.open`
3. show the error

**Comment by folke** [comment] 2024-03-29 09:22
Still works for me.
What is the full stacktrace?

**Comment by folke** [comment] 2024-03-29 09:22
Are you using the latest trouble version?

**Comment by folke** [comment] 2024-03-29 09:42
Was able to reproduce. Should be fixed now!

**Closed by folke** 2024-03-29 09:42 UTC
Labels: bug v3

**Comment by ShiChenCong** [comment] 2024-03-29 09:45
I have just created the minimal reproduce repo 😂
After update, It works perfectly, Thank you for the work!
