### ISSUE TITLE
Trouble buffer totally empty for all modes

### ISSUE THREAD

**Issue by MarcelRobitaille** [folke/trouble.nvim#211] opened 2022-09-10 18:37 UTC
I have just installed this plugin. When I run `:Trouble` (or `:Trouble <mode>` for any mode), the buffer that opens at the bottom of the screen is always totally empty.

I have a properly configured LSP and have opened a file I know to have errors. The diagnostics are showing up for that file with [LSP saga](https://github.com/glepnir/lspsaga.nvim). 

Here is a minimal vim config that reproduces the issue (`nvim -u minimal.vim`).

`minimal.vim`
```vim
call plug#begin('/home/marcel/.config/nvim/plugged')
	Plug 'neovim/nvim-lspconfig'
	Plug 'folke/trouble.nvim'
call plug#end()

lua << EOF
  require'lspconfig'.rust_analyzer.setup { }

  require("trouble").setup {
    -- your configuration comes here
    -- or leave it empty to use the default settings
    -- refer to the configuration section below
  }
EOF

```

`LspInfo`
```
 Use [q] or [Esc] to quit the window
 
 Language client log: /home/marcel/.cache/nvim/lsp.log
 Detected filetype:   rust
 
 1 client(s) attached to this buffer: 
 
 Client: rust_analyzer (id: 1, pid: 521209, bufnr: [1])
 	filetypes:       rust
 	autostart:       true
 	root directory:  /home/marcel/code/rust_motd
 	cmd:             rust-analyzer
 
 Configured servers list: rust_analyzer
```

nvim version: v0.8.0-dev
trouble version: 929315ea

**Comment by bwidawsk** [comment] 2022-12-19 16:57
I have the same/similar issue. Trouble was previously working for me. 

`:lua = vim.diagnostic.get()` shows the proper diagnostic list. I have no clue how to even start figuring out what's going on.

**Comment by leekool** [comment] 2023-04-15 15:27
I have the same issue. Did either of you find a solution?

**Comment by smartinellimarco** [comment] 2023-05-06 20:21
I have it set up with lsp-zero and have the same issue

**Comment by bbalanza** [comment] 2023-06-28 00:01
I am having the same issue with lazy.nvim :/ Has anyone found a solution?

**Comment by bbalanza** [comment] 2023-06-28 00:18
Actually, I think I might have found the problem. The issue is that trouble will silently save the toggle mode. So if for instance, if you use `:TroubleToggle quickfix` first (which comes up empty), and then use `:TroubleToggle` again, it will automatically use `:TroubleToggle quickfix`. Try `:TroubleToggle workspace_diagnostics` and see if that works.

**Comment by folke** [comment] 2024-03-29 07:54
Development on the main branch is EOL.

Trouble has been rewritten and will be merged in main soon.

This issue/feature either no longer exists or has been implemented on dev.

For more info, see https://github.com/folke/trouble.nvim/tree/dev

**Closed by folke** 2024-03-29 07:54 UTC
Labels: fixed v3

**Comment by theunrealtarik** [comment] 2025-05-03 14:41
Nope, the issue still exist even on the newest version, after the rewrite, but I don't believe `folke/trouble.nvim` is to blame here since nvim's quick fix list's buffer also comes out empty.


![Image](https://github.com/user-attachments/assets/3e90d7fc-78e5-45a3-bee5-f1c2f4b294d5)


![Image](https://github.com/user-attachments/assets/06d6367b-36e6-4eaf-a361-ebd1f6889fff)
