### ISSUE TITLE
feature: Jump to current line in Trouble list

### ISSUE THREAD

**Issue by TroySigX** [folke/trouble.nvim#246] opened 2023-01-07 00:27 UTC
### Did you check the docs?

- [X] I have read all the trouble.nvim docs

### Is your feature request related to a problem? Please describe.

Let's say I'm on the line 200 in the editor, and there's an error on this line. I want to open the Trouble list (location list in my case) and immediately jump to the error on that 200th line.

### Describe the solution you'd like

 Create a mapping (say Ctrl-Enter) to open the trouble list and immediately navigate to the error on the current line.

### Describe alternatives you've considered

Not yet.

**Comment by DanielPower** [comment] 2023-04-16 05:28
I believe this is a duplicate of #32

**Closed** 2023-04-30 04:34 UTC
Labels: enhancement
